DROP DATABASE PHOTOSHARE;
CREATE DATABASE PHOTOSHARE;

USE PHOTOSHARE;

CREATE TABLE USER (
  UID INT NOT NULL AUTO_INCREMENT,
  EMAIL VARCHAR(30) UNIQUE NOT NULL,
  PASSWORD VARCHAR(30) NOT NULL,
  FNAME VARCHAR(30) NOT NULL,
  LNAME VARCHAR(30) NOT NULL,
  GENDER VARCHAR(10),
  DOB DATE NOT NULL,
  HOMETOWN VARCHAR(30),
  PRIMARY KEY (UID)
);

CREATE TABLE FRIENDSHIP (
  UID1 INT NOT NULL,
  UID2 INT NOT NULL,
  PRIMARY KEY (UID1, UID2),
  FOREIGN KEY (UID1) REFERENCES USER (UID) ON DELETE CASCADE,
  FOREIGN KEY (UID2) REFERENCES USER (UID) ON DELETE CASCADE
);

CREATE TABLE ALBUM (
  AID INT NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(30) NOT NULL,
  DOC TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UID INT NOT NULL,
  PRIMARY KEY (AID),
  FOREIGN KEY (UID) REFERENCES USER (UID) ON DELETE CASCADE
);

CREATE TABLE PHOTO (
  PID INT NOT NULL AUTO_INCREMENT,
  CAPTION VARCHAR(200),
  DATA VARCHAR(100) NOT NULL,
  AID INT NOT NULL,
  PRIMARY KEY (PID),
  FOREIGN KEY (AID) REFERENCES ALBUM (AID) ON DELETE CASCADE
);

CREATE TABLE TAG (
  HASHTAG VARCHAR(30) NOT NULL,
  PRIMARY KEY (HASHTAG)
);

CREATE TABLE ASSOCIATE (
  PID INT NOT NULL,
  HASHTAG VARCHAR(30) NOT NULL,
  PRIMARY KEY (PID, HASHTAG),
  FOREIGN KEY (PID) REFERENCES PHOTO (PID) ON DELETE CASCADE,
  FOREIGN KEY (HASHTAG) REFERENCES TAG (HASHTAG) ON DELETE CASCADE
);

CREATE TABLE COMMENT (
  CID INT NOT NULL AUTO_INCREMENT,
  CONTENT VARCHAR(200) NOT NULL,
  DOC TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UID INT NOT NULL,
  PID INT NOT NULL,
  PRIMARY KEY (CID),
  FOREIGN KEY (UID) REFERENCES USER (UID) ON DELETE CASCADE,
  FOREIGN KEY (PID) REFERENCES PHOTO (PID) ON DELETE CASCADE
);

CREATE TABLE FAVORITE (
  UID INT NOT NULL,
  PID INT NOT NULL,
  DOC TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (UID, PID),
  FOREIGN KEY (UID) REFERENCES USER (UID) ON DELETE CASCADE,
  FOREIGN KEY (PID) REFERENCES PHOTO (PID) ON DELETE CASCADE
);

INSERT INTO USER (EMAIL, PASSWORD, FNAME, LNAME, DOB) VALUES ('anonymous@photoshare.com', 'password', 'Anonymous', 'User', '2017-10-01');
INSERT INTO USER (EMAIL, PASSWORD, FNAME, LNAME, DOB) VALUES ('zqzhang@bu.edu', 'hello', 'Zuoqi', 'Zhang', '2017-10-01');
INSERT INTO USER (EMAIL, PASSWORD, FNAME, LNAME, DOB) VALUES ('chahuang@bu.edu', 'hello', 'Charles', 'Huang', '2017-10-01');
INSERT INTO USER (EMAIL, PASSWORD, FNAME, LNAME, DOB) VALUES ('test@bu.edu', 'test', 'test', 'test', '2017-10-01');
INSERT INTO USER (EMAIL, PASSWORD, FNAME, LNAME, DOB) VALUES ('aa@aa.com', 'aa', 'aa', 'aa', '2017-10-01');
INSERT INTO USER (EMAIL, PASSWORD, FNAME, LNAME, DOB) VALUES ('bb@bb.com', 'bb', 'bb', 'bb', '2017-10-01');
INSERT INTO USER (EMAIL, PASSWORD, FNAME, LNAME, DOB) VALUES ('cc@cc.com', 'cc', 'cc', 'cc', '2017-10-01');
INSERT INTO USER (EMAIL, PASSWORD, FNAME, LNAME, DOB) VALUES ('dd@dd.com', 'dd', 'dd', 'dd', '2017-10-01');
INSERT INTO USER (EMAIL, PASSWORD, FNAME, LNAME, DOB) VALUES ('ee@ee.com', 'ee', 'ee', 'ee', '2017-10-01');
INSERT INTO USER (EMAIL, PASSWORD, FNAME, LNAME, DOB) VALUES ('ff@ff.com', 'ff', 'ff', 'ff', '2017-10-01');
INSERT INTO USER (EMAIL, PASSWORD, FNAME, LNAME, DOB) VALUES ('ab@ab.com', 'ab', 'ab', 'ab', '2017-10-01');
INSERT INTO USER (EMAIL, PASSWORD, FNAME, LNAME, DOB) VALUES ('ac@ac.com', 'ac', 'ac', 'ac', '2017-10-01');
INSERT INTO USER (EMAIL, PASSWORD, FNAME, LNAME, DOB) VALUES ('ad@ad.com', 'ad', 'ad', 'ad', '2017-10-01');
INSERT INTO USER (EMAIL, PASSWORD, FNAME, LNAME, DOB) VALUES ('ba@ba.com', 'ba', 'ba', 'ba', '2017-10-01');
INSERT INTO USER (EMAIL, PASSWORD, FNAME, LNAME, DOB) VALUES ('ca@ca.com', 'ca', 'ca', 'ca', '2017-10-01');
INSERT INTO USER (EMAIL, PASSWORD, FNAME, LNAME, DOB) VALUES ('da@da.com', 'da', 'da', 'da', '2017-10-01');

INSERT INTO FRIENDSHIP VALUES (2, 3);
INSERT INTO FRIENDSHIP VALUES (3, 2);
INSERT INTO FRIENDSHIP VALUES (2, 4);
INSERT INTO FRIENDSHIP VALUES (4, 2);
INSERT INTO FRIENDSHIP VALUES (4, 5);
INSERT INTO FRIENDSHIP VALUES (5, 4);
INSERT INTO FRIENDSHIP VALUES (7, 9);
INSERT INTO FRIENDSHIP VALUES (9, 7);
INSERT INTO FRIENDSHIP VALUES (4, 11);
INSERT INTO FRIENDSHIP VALUES (11, 4);
INSERT INTO FRIENDSHIP VALUES (4, 8);
INSERT INTO FRIENDSHIP VALUES (8, 4);


INSERT INTO ALBUM (NAME, DOC, UID) VALUES ('Default', CURRENT_TIMESTAMP, 4);
INSERT INTO ALBUM (NAME, DOC, UID) VALUES ('Test', CURRENT_TIMESTAMP, 4);
INSERT INTO ALBUM (NAME, DOC, UID) VALUES ('New', CURRENT_TIMESTAMP, 2);
INSERT INTO ALBUM (NAME, DOC, UID) VALUES ('New', CURRENT_TIMESTAMP, 3);
INSERT INTO ALBUM (NAME, DOC, UID) VALUES ('New', CURRENT_TIMESTAMP, 4);
INSERT INTO ALBUM (NAME, DOC, UID) VALUES ('New', CURRENT_TIMESTAMP, 5);
INSERT INTO ALBUM (NAME, DOC, UID) VALUES ('New', CURRENT_TIMESTAMP, 6);
INSERT INTO ALBUM (NAME, DOC, UID) VALUES ('New', CURRENT_TIMESTAMP, 7);
INSERT INTO ALBUM (NAME, DOC, UID) VALUES ('New', CURRENT_TIMESTAMP, 8);
INSERT INTO ALBUM (NAME, DOC, UID) VALUES ('New', CURRENT_TIMESTAMP, 9);
INSERT INTO ALBUM (NAME, DOC, UID) VALUES ('New', CURRENT_TIMESTAMP, 10);
INSERT INTO ALBUM (NAME, DOC, UID) VALUES ('New', CURRENT_TIMESTAMP, 11);
INSERT INTO ALBUM (NAME, DOC, UID) VALUES ('New', CURRENT_TIMESTAMP, 12);

INSERT INTO PHOTO (CAPTION, DATA, AID) VALUES ('Photo 1', '1.jpg', 1);
INSERT INTO PHOTO (CAPTION, DATA, AID) VALUES ('Photo 2', '2.jpg', 2);
INSERT INTO PHOTO (CAPTION, DATA, AID) VALUES ('Photo 3', '3.jpg', 2);
INSERT INTO PHOTO (CAPTION, DATA, AID) VALUES ('Photo 4', '4.png', 3);
INSERT INTO PHOTO (CAPTION, DATA, AID) VALUES ('Photo 5', '5.png', 3);

INSERT INTO TAG VALUES ('boston');
INSERT INTO TAG VALUES ('icon');
INSERT INTO TAG VALUES ('test');
INSERT INTO TAG VALUES ('new');
INSERT INTO TAG VALUES ('white');

INSERT INTO ASSOCIATE VALUES (1, 'boston');
INSERT INTO ASSOCIATE VALUES (1, 'test');
INSERT INTO ASSOCIATE VALUES (2, 'icon');
INSERT INTO ASSOCIATE VALUES (3, 'icon');
INSERT INTO ASSOCIATE VALUES (4, 'white');
INSERT INTO ASSOCIATE VALUES (4, 'test');
INSERT INTO ASSOCIATE VALUES (4, 'new');
INSERT INTO ASSOCIATE VALUES (5, 'white');
INSERT INTO ASSOCIATE VALUES (5, 'new');

INSERT INTO COMMENT (CONTENT, DOC, UID, PID) VALUES ('Comment from anonymous user.', CURRENT_TIMESTAMP, 1, 1);
INSERT INTO COMMENT (CONTENT, DOC, UID, PID) VALUES ('2nd comment.', CURRENT_TIMESTAMP, 3, 1);
INSERT INTO COMMENT (CONTENT, DOC, UID, PID) VALUES ('1st', CURRENT_TIMESTAMP, 3, 2);
INSERT INTO COMMENT (CONTENT, DOC, UID, PID) VALUES ('1st', CURRENT_TIMESTAMP, 3, 3);
INSERT INTO COMMENT (CONTENT, DOC, UID, PID) VALUES ('Comment from test user.', CURRENT_TIMESTAMP, 4, 4);
INSERT INTO COMMENT (CONTENT, DOC, UID, PID) VALUES ('Comment from test user.', CURRENT_TIMESTAMP, 4, 5);

INSERT INTO FAVORITE VALUES (2, 1, CURRENT_TIMESTAMP);
INSERT INTO FAVORITE VALUES (3, 1, CURRENT_TIMESTAMP);
INSERT INTO FAVORITE VALUES (5, 1, CURRENT_TIMESTAMP);
INSERT INTO FAVORITE VALUES (7, 1, CURRENT_TIMESTAMP);
INSERT INTO FAVORITE VALUES (9, 1, CURRENT_TIMESTAMP);
INSERT INTO FAVORITE VALUES (10, 1, CURRENT_TIMESTAMP);
INSERT INTO FAVORITE VALUES (3, 2, CURRENT_TIMESTAMP);
INSERT INTO FAVORITE VALUES (9, 2, CURRENT_TIMESTAMP);
INSERT INTO FAVORITE VALUES (10, 2, CURRENT_TIMESTAMP);
INSERT INTO FAVORITE VALUES (2, 4, CURRENT_TIMESTAMP);
INSERT INTO FAVORITE VALUES (4, 4, CURRENT_TIMESTAMP);
INSERT INTO FAVORITE VALUES (5, 4, CURRENT_TIMESTAMP);
INSERT INTO FAVORITE VALUES (4, 5, CURRENT_TIMESTAMP);