DROP DATABASE PHOTOSHARE;
CREATE DATABASE PHOTOSHARE;

USE PHOTOSHARE;

CREATE TABLE USER (
  UID INT NOT NULL AUTO_INCREMENT,
  EMAIL VARCHAR(30) UNIQUE,
  PASSWORD VARCHAR(30) NOT NULL,
  FNAME VARCHAR(30) NOT NULL,
  LNAME VARCHAR(30) NOT NULL,
  GENDER VARCHAR(10) NOT NULL,
  DOB DATE,
  HOMETOWN VARCHAR(30),
  PRIMARY KEY (UID)
);

CREATE TABLE FRIENDSHIP (
  UID1 INT NOT NULL,
  UID2 INT NOT NULL,
  PRIMARY KEY (UID1, UID2),
  FOREIGN KEY (UID1) REFERENCES USER (UID) ON DELETE CASCADE,
  FOREIGN KEY (UID2) REFERENCES USER (UID) ON DELETE CASCADE
);

CREATE TABLE ALBUM (
  AID INT NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(30) NOT NULL,
  DOC TIMESTAMP NOT NULL,
  UID INT NOT NULL,
  PRIMARY KEY (AID),
  FOREIGN KEY (UID) REFERENCES USER (UID) ON DELETE CASCADE
);

CREATE TABLE PHOTO (
  PID INT NOT NULL AUTO_INCREMENT,
  CAPTION VARCHAR(200),
  DATA BLOB NOT NULL,
  AID INT NOT NULL,
  PRIMARY KEY (PID),
  FOREIGN KEY (AID) REFERENCES ALBUM (AID) ON DELETE CASCADE
);

CREATE TABLE TAG (
  HASHTAG VARCHAR(30) NOT NULL,
  PRIMARY KEY (HASHTAG)
);

CREATE TABLE ASSOCIATE (
  PID INT NOT NULL,
  HASHTAG VARCHAR(30) NOT NULL,
  PRIMARY KEY (PID, HASHTAG),
  FOREIGN KEY (PID) REFERENCES PHOTO (PID) ON DELETE CASCADE,
  FOREIGN KEY (HASHTAG) REFERENCES TAG (HASHTAG) ON DELETE CASCADE
);

CREATE TABLE COMMENT (
  CID INT NOT NULL AUTO_INCREMENT,
  CONTENT VARCHAR(200) NOT NULL,
  DOC TIMESTAMP NOT NULL,
  UID INT NOT NULL,
  PID INT NOT NULL,
  PRIMARY KEY (CID),
  FOREIGN KEY (UID) REFERENCES USER (UID) ON DELETE CASCADE,
  FOREIGN KEY (PID) REFERENCES PHOTO (PID) ON DELETE CASCADE
);

CREATE TABLE FAVORITE (
  UID INT NOT NULL,
  PID INT NOT NULL,
  DOC TIMESTAMP NOT NULL,
  PRIMARY KEY (UID, PID),
  FOREIGN KEY (UID) REFERENCES USER (UID) ON DELETE CASCADE,
  FOREIGN KEY (PID) REFERENCES PHOTO (PID) ON DELETE CASCADE
);